### PR TITLE
remove node cache in the final docker image (~/.npm/_cacache/ folder) -> 11% smaller image

### PR DESCRIPTION
**Pull request by caioau**
Hello @WeeJeWel, I loved the project! Keep up the awesome work :)

Out of curiosity, I ran the dive tool (https://github.com/wagoodman/dive) I find some node cache files ~/.npm/_cacache/

I changed the Dockerfile to remove them making the final docker image smaller, previous it was 143MB now 132MB (uncompressed) an 8% improvement.

Signed-off-by: caioau <caio.volpato@riseup.net>

### CODE REVIEW

**Comment by ffoxin** [comment]
@caioau hi!
what about appending next line after your changes `RUN mv /app/node_modules/ /node_modules/` also to your call to `RUN` command using `&&`?

**Comment by caioau** [comment]
Thanks @ffoxin! I did that (https://github.com/WeeJeWel/wg-easy/pull/170/commits/18a259bff1eee4a81028b618dabe817b55dc241f) and a couple MBs were, now the image is reduced by 11%.

**Comment by WeeJeWel** [comment]
Fixed differently (imho more elegantly) in https://github.com/WeeJeWel/wg-easy/commit/bbd19b7a6f390d95d80aab75271a24b92f6c591e

**Comment by ffoxin** [comment]
> Fixed differently (imho more elegantly) in [bbd19b7](https://github.com/WeeJeWel/wg-easy/commit/bbd19b7a6f390d95d80aab75271a24b92f6c591e)

And the same thing there: three sequential `RUN` in lines 31-39. Merging it into single `RUN ... && ...` saves space.

**Pull request closed without merging**
