### PR TITLE
docs: add PORT option to readme

### PR DESCRIPTION
**Pull request by fneiraj**
add the PORT option to define the ui internal port.

### CODE REVIEW

**Comment by dacianpeng** [comment]
I spend about 2 hours to find this solution and finally end up here

**Comment by WeeJeWel** [comment]
This is only confusing, why would you want to change this?

**Comment by fneiraj** [comment]
I have wg-easy in a docker container with macvlan, and with a dns server I resolve it to vpn.local (for example), so I don't want to type vpn.local:51821 to enter the UI, I just want to type vpn.local

**Comment by lluisd** [comment]
awesome, please merge it, very useful when we run it as network_mode="host"

**Comment by WeeJeWel** [comment]
Similar: https://github.com/WeeJeWel/wg-easy/pull/548

**Pull request closed without merging**
