### PR TITLE
Expose metrics in Prometheus format

### PR DESCRIPTION
**Pull request by vojtad**
This PR implements metrics in Prometheus format at `/metrics` endpoints. HTTP Basic authorization is supported.

It can be configured via `METRICS_ENABLED`, `METRICS_USER` and `METRICS_PASSWORD` environment variables. More info in README.md.

WireGuard metric names and labels are inspired by [prometheus_wireguard_exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter) to make them compatible and to make existing Grafana dashboards work with `wg-easy`.

### Example WireGuard metrics

```
# HELP wireguard_sent_bytes_total Bytes sent to the peer
# TYPE wireguard_sent_bytes_total counter
wireguard_sent_bytes_total{interface="wg0",public_key="QpPNe62/SuCUSEkBTu3r2U0ihe2UrDspxUUgk195zmc=",allowed_ips="10.112.112.2/32",friendly_name="Test User 1",enabled="true"} 0
wireguard_sent_bytes_total{interface="wg0",public_key="2AyHc7bRYJUJdx9UG87QmZDolj8xh6CORgP0PA28JT4=",allowed_ips="10.112.112.3/32",friendly_name="Test User 2",enabled="true"} 95788240

# HELP wireguard_received_bytes_total Bytes received from the peer
# TYPE wireguard_received_bytes_total counter
wireguard_received_bytes_total{interface="wg0",public_key="QpPNe62/SuCUSEkBTu3r2U0ihe2UrDspxUUgk195zmc=",allowed_ips="10.112.112.2/32",friendly_name="Test User 1",enabled="true"} 0
wireguard_received_bytes_total{interface="wg0",public_key="2AyHc7bRYJUJdx9UG87QmZDolj8xh6CORgP0PA28JT4=",allowed_ips="10.112.112.3/32",friendly_name="Test User 2",enabled="true"} 54389700

# HELP wireguard_latest_handshake_seconds Seconds from the last handshake
# TYPE wireguard_latest_handshake_seconds gauge
wireguard_latest_handshake_seconds{interface="wg0",public_key="QpPNe62/SuCUSEkBTu3r2U0ihe2UrDspxUUgk195zmc=",allowed_ips="10.112.112.2/32",friendly_name="Test User 1",enabled="true"} 0
wireguard_latest_handshake_seconds{interface="wg0",public_key="2AyHc7bRYJUJdx9UG87QmZDolj8xh6CORgP0PA28JT4=",allowed_ips="10.112.112.3/32",friendly_name="Test User 2",enabled="true"} 1633967910

# HELP wireguard_persistent_keepalive_seconds Seconds between each persistent keepalive packet
# TYPE wireguard_persistent_keepalive_seconds gauge
wireguard_persistent_keepalive_seconds{interface="wg0",public_key="QpPNe62/SuCUSEkBTu3r2U0ihe2UrDspxUUgk195zmc=",allowed_ips="10.112.112.2/32",friendly_name="Test User 1",enabled="true"} 0
wireguard_persistent_keepalive_seconds{interface="wg0",public_key="2AyHc7bRYJUJdx9UG87QmZDolj8xh6CORgP0PA28JT4=",allowed_ips="10.112.112.3/32",friendly_name="Test User 2",enabled="true"} 0
```

### CODE REVIEW

**Comment by vojtad** [comment]
@WeeJeWel Any thoughts on this? Do you have any suggestions what you would like to change if anything?

**Comment by benisai** [comment]
> Personally I wouldn't use it, but metrics are nice :)
> 
> What I would prefer:
> 
> * Visible metrics in the UI, e.g. a chart per user.
> * That requires a generic `getMetrics` endpoint.
> * Some adapter structure to transform metrics into opinionated format, e.g. Prometheus.

Hello, any update on this :)

**Comment by WeeJeWel** [comment]
FYI I've added client-side charts for tx/rx.

**Comment by WeeJeWel** [comment]
Closed due to inactivity.

**Comment by Ownercz** [comment]
> Closed due to inactivity.

+1 for prometheus metrics, do you need anything before merging this?

**Comment by michaelmcmillan** [comment]
@WeeJeWel: I would reconsider this PR if I were you. Prometheus metrics would be great, and it doesn't get in the way of anything.

**Comment by centralhardware** [comment]
it's no big problem to run wireguard prometheus exporter as separated container

**Comment by michaelmcmillan** [comment]
Sure, but running two web servers suck.

**Comment by vojtad** [comment]
I would be happy to refresh the code and send a new PR. Is there a chance this gets merged?

We are still using this, however, I would like to run a vanilla wg-easy container. We are now deciding whether we should run a separate exporter or not.

**Pull request closed without merging**
