### PR TITLE
README : Improve Docker Installation instructions

### PR DESCRIPTION
**Pull request by nicolasverlhiac**

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Why is this better?

**Comment by nicolasverlhiac** [comment]
Hi @WeeJeWel,

The convenience script is not recommended for production usage.
https://docs.docker.com/engine/install/

I thought it would help to have both approaches available for the Docker setup.

What do you think about it?

Thank you

**Comment by ffoxin** [comment]
> Hi @WeeJeWel,
> 
> The convenience script is not recommended for production usage. https://docs.docker.com/engine/install/
> 
> I thought it would help to have both approaches available for the Docker setup.
> 
> What do you think about it?
> 
> Thank you

Are you sure that adding static manual to README.md is better than adding just a link to the up-to-date manual?

**Comment by nicolasverlhiac** [comment]
It is indeed possible to keep only this part: 

---
### 1. Install Docker

If you haven't installed Docker yet, install it by running:
You can follow this instruction, but don't forget to take a look to the [Docker documentation](https://docs.docker.com/engine/install/).

**Pull request closed without merging**
