### PR TITLE
Add PORT environment variable in README.md

### PR DESCRIPTION
**Pull request by rahilarious**

### CODE REVIEW

**Comment by WeeJeWel** [comment]
It’s just more confusing because Docker maps the port already.

**Comment by rahilarious** [comment]
What if user is using `--network=host` and want webUI on other port ?

**Comment by WeeJeWel** [comment]
Then they set the PORT environment variable :)

**Comment by rahilarious** [comment]
and how would they know that env is configurable when its absent in docs?

**Comment by WeeJeWel** [comment]
﻿The docs are for the Docker usecase only. If they want to be adventurous, they can dive into the source files.Sent from my iPhoneOn 17 May 2023, at 10:51, Rahil Bhimjiani ***@***.***> wrote:﻿
and how would they know that env is configurable when its absent in docs?

**Comment by rahilarious** [comment]
It is an official docker-cli command switch but Your project your rules. Respecting that. 

Thanks for minimal & pretty project.

**Comment by WeeJeWel** [comment]
You can always write a wiki article for running Docker in host mode :)

**Comment by rahilarious** [comment]
That would be the shortest article EVER ;)

**Pull request closed without merging**
