### PR TITLE
add wireguard device parameter

### PR DESCRIPTION
**Pull request by joeroback**
Fix hardcoding of `eth0` device name.

### CODE REVIEW

**Comment by joeroback** [comment]
is this project dead? or in need of a maintainer?

**Review by WeeJeWel — APPROVED** [review]

**Comment by WeeJeWel** [comment]
Thanks, great contribution!

**Comment by TCB13** [comment]
Thank you, please merge this into production. :)

**Comment by 99kennetn** [comment]
this would be nice to be added to the latest version of the docker container

**Pull request merged**
