### PR TITLE
Add last ip number selection

### PR DESCRIPTION
**Pull request by rapejim**
- Added last IP number selection for new client (auto if empty)
- Added sort clients on webUI by last IP number

image
image
image

### CODE REVIEW

**Comment by aniqueta** [comment]
I like this change. I was migrating over an old config, and so just went through to manually set things in the JSON… It would also be nice to be able to set the "server" IP (which I did by editing WireGuard.js).

**Comment by WeeJeWel** [comment]
This is very nice functionality. I've given it some thought and came up with an (imho) better UX:

* [New Client] dialog doesn't change
* When hovering over the IP address in the list, a small edit-icon (pencil) appears. Clicking it makes the IP address an inline-textfield.
* We do the same for name and solve #12

**Comment by WeeJeWel** [comment]
FYI I won't merge this until it works like I suggested, because this code is too different :)

**Comment by rapejim** [comment]
> FYI I won't merge this until it works like I suggested, because this code is too different :)

I don't have enough knowledge to develop your suggestion "BLABLABLABLA" but I just uploaded a commit with the changes to edit the client using a pencil icon next to the delete icon and make the changes in a modal window like the new client.

image
image
image

I hope that these changes I have made are enough to your satisfaction to merge them.


Ah! si quieres probar los cambios fácilmente, en mi fork yo he unido los cambios en la rama de producción y por tanto puedes probarlos tan fácilmente como usando (aunque sea temporalmente) my imagen de docker `rapejim/wg-easy`

**Comment by WeeJeWel** [comment]
This is now included in release 2.

**Pull request closed without merging**
