### PR TITLE
Add iptables support for WG_ALLOWED_IPS

### PR DESCRIPTION
**Pull request by Retloldin**
By default this WireGuard server implementation doesn't filter the destination IP addresses that the client requests.

Only with the AllowedIPs field of the configuration file the end users can access any destination if they edit it, creating a false security in the container configuration.

Adding the use of iptables as a filter for accessible networks brings up the security that the WG ALLOWED_IPS field to the user.

### CODE REVIEW

**Comment by psycmos** [comment]
Subscribed ;)

**Review by psycmos — CHANGES_REQUESTED** [review]
It's possible to include Variable Port Restrict like Allowed IP?

**Comment by Retloldin** [comment]
> It's possible to include Variable Port Restrict like Allowed IP?

This would require changing the input format of the WG_ALLOWED_IPS variable or creating a new one to define the ports to be filtered with iptables.

The proposed change in this request doesn't require any changes from the end users in case of a Docker update.

**Comment by psycmos** [comment]
> > It's possible to include Variable Port Restrict like Allowed IP?
> 
> This would require changing the input format of the WG_ALLOWED_IPS variable or creating a new one to define the ports to be filtered with iptables.
> 
> The proposed change in this request doesn't require any changes from the end users in case of a Docker update.

You are right, it require a new variable, i will create a new request :D
Maybe the creators can change the default template ;)

**Comment by WeeJeWel** [comment]
You can now overwrite all iptables with env var `WG_POST_UP`.

**Pull request closed without merging**
