### PR TITLE
[Feature] Add dark mode 🌙

### LINKED ISSUE #163: Dark Theme possible?
Love the project, but the all white is killing my eyes. Any way to have a dark mode theme?

### PR DESCRIPTION
**Pull request by Teraskull**
This PR contains the following changes:

* Add dark mode using the new `dark:` class in Tailwind 3.
* Add theme switch button.
* Replace all dark red colors with pastel alternatives in dark mode.
* Fix static HTML elements flashing when reloading page.
* Fix mobile layout and overflowing elements.
* Update `tailwind.min.css` to only include used classes, which reduces the size from `2859KB` to just `20KB`.
> Future changes to the style will require to use a CDN for development and tree shaking the file again.

This PR also changes a few things in light mode:
* The toggles are now green (Red is not a good option for `On` state).
* Removed the double border from the `Clients` header.
* Removed the bottom border/divider from the last table child.

## Screenshots:
wireguard_dashboard
wireguard_login
wireguard_modal

### Before vs After (light/dark):
image

All elements should be properly styled in dark mode, including the Update banner. If I missed anything, let me know. (Closes #163)

### CODE REVIEW

**Comment by whatdemocracy** [comment]
Love it! Very good job!!!

**Comment by benisai** [comment]
Love it. God bless you. The dev wouldn't do it. But man bless your heart @Teraskull

**Comment by WeeJeWel** [comment]
Looks nice, but I’d prefer it if you keep the WireGuard color scheme instead of this neutral style.

**Comment by Teraskull** [comment]
@WeeJeWel I know, but sorry, the wireguard scheme just couldn't play right with dark colors and contrast.

**Comment by benisai** [comment]
I'm excited for this PR :) 🙏✌️

**Comment by wjbridge** [comment]
Any estimate on when this can be merged into the project for a release? I love it!

**Comment by WeeJeWel** [comment]
No, I think the color scheme looks very boring and misses all WireGuard branding :/

**Comment by benisai** [comment]
> No, I think the color scheme looks very boring and misses all WireGuard branding :/

Can The branding be added? I think the color looks amazing in my opinion. :) Would it be possible to have a switch in the web browser from original to dark mode? :) 👍👍👍👍

**Comment by callumgare** [comment]
@WeeJeWel I definitely understand the desire to the WireGuard branding, I think having personality in design is really valuable. Although I'm sure you'd agree accessibility and comfort are also really valuable and there's no reason you can't have both. What would it take for you to feel like the UI keeps the brand while also ensuring there's a high enough colour contrast in dark mode?  For example say the dark red of the wireguard brand was used in the border of the central panel instead and a more neutral color was used for the switch "on"/"off" text inside the switch to indicate state.

**Comment by ad84** [comment]
> 

The wiregaurd android client gui seems made for accessibility and readability in dark mode. There's no branding colours, just the wiregaurd logo.

**Comment by Archef2000** [comment]
When will it be merged ?

**Comment by JapCLoN** [comment]
I've added your dark mode pr to my non docker repo, added you to the credits for dark mode

**Comment by benisai** [comment]
@WeeJeWel  -- has this been merged yet? Looking forward to it

**Comment by WeeJeWel** [comment]
No. I'm only going to reconsider when the color scheme is black-ish (not blue-ish) and WireGuard-red-ish.

**Comment by rcdailey** [comment]
@WeeJeWel With respect, why not accept what many users are waiting for here? The point is that this theme does not blind me when I open the website. Seems like you are holding off a good thing for perfection. It's been half a year; I think it's time to stop nitpicking and merge.

**Comment by benisai** [comment]
I would agree with @rcdailey

**Comment by benisai** [comment]
> No. I'm only going to reconsider when the color scheme is black-ish (not blue-ish) and WireGuard-red-ish.

Why? All Black and red is a eye sore. Terrible color choice.

**Comment by WeeJeWel** [comment]
Because [it's my project](https://github.com/WeeJeWel/how-to-be-a-great-programmer/blob/main/say-no.md). If you want changes, fork it. It's as simple as that guys, this is how open source works.

**Comment by ad84** [comment]
That's the community spirit! 😉

**Comment by benisai** [comment]
You might as well just close the PR if it's never going to happen.

**Comment by benisai** [comment]
And to be honest, the reason we don't want to fork is because we really like the work YOU did. 👍

**Comment by WeeJeWel** [comment]
> And to be honest, the reason we don't want to fork is because we really like the work YOU did. 👍

You might mean: you want me to maintain this change ;-)

Any fork already contains the work I did :)

**Comment by benisai** [comment]
@WeeJeWel - yes ;)

Can you merge it and make it an option at least? With a switch or something in the config?

**Comment by WeeJeWel** [comment]
Not until the design looks better by keeping the WireGuard branding in place.

**Comment by JoryHogeveen** [comment]
> No. I'm only going to reconsider when the color scheme is black-ish (not blue-ish) and WireGuard-red-ish.

I've got to agree with @WeeJeWel on this one. Besides, not much effort to change the colors for the PR author I imagine, most of the work is already done here.
I prefer dark mode as well but really do not like the blue/green color scheme proposed here.

**Comment by divadsn** [comment]
I'd agree as well, a dark-gray and WireGuard red style would fit much better

**Comment by benisai** [comment]
At this point, I'll take anything. I can't stand the white page anymore.

**Comment by Butterkeks1000** [comment]
Any news to this pr?

**Comment by benisai** [comment]
I was just wondering the same thing

**Comment by JoryHogeveen** [comment]
The plugin author already mentioned his requirements.
I guess that so long as this PR isn't updated accordingly nothing will happen.

**Comment by Teraskull** [comment]
Ok, I guess it's time for me to reply too.

Sorry everyone, but I will not change the color scheme.

I respect Emile's design view, and his choice to not merge this PR, but I also expect my views to be respected, and him saying some color scheme is "better" because it has Wireguard colors, is very subjective.

Anyways, I am not going to change the colors since that is my design view, which I, and many others that upvoted this PR, like.

It is absolutely okay to not come to a design agreement. It is also okay to not accept changes if you don't like them. But remember that it goes both ways. I do not like the Wireguard colors contrasting with the dark theme.

I understand Emile not wanting to maintain the changes. Unfortunately, I also don't have time or motivation to maintain a fork. So if anyone wants to make a fork with my changes, they're welcome.

I hope you understand, and thank you for the support.

**Comment by benisai** [comment]
I wish @WeeJeWel would accept this, it's super nice

**Pull request closed without merging**
