### PR TITLE
Added docker secrets support for PASSWORD and WG_HOST in Docker Swarm

### PR DESCRIPTION
**Pull request by niem94**
#168 

@WeeJeWel Can you test if this works as expected for normal use cases? I added a docker-compose.dev-secrets.yml file as well with some guidance on how to test it with docker swarm. 👍🏻

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Hm. This adds complexity for a specific use case, and I don't really understand how this is safer?

**Comment by WeeJeWel** [comment]
You say ‘the repo’, as in, do you commit your docker compose file?

In that case, just put them in ‘.env’!

**Comment by niem94** [comment]
Yes I do, and I see setting the env variables elsewhere could be one way to make it work, but I would still prefer if I would be able to set the env variables from docker secrets. This is what I am used to do with all my stacks, and I would like to be consistent. There are several reasons why:

1. Docker will tell me if I have not set the required secrets for a stack to run.
2. It is a solution that solely requires docker. Low maintenance
3. It provides a layer of abstraction between the containers and their environment.

Is there no interest in supporting this? Otherwise I do not mind making a fork and maintaining a version of wg-easy that is more centered around my usecase.

**Comment by niem94** [comment]
I just researched this a bit, as I was a bit confused if I was missing something. It seems I was. I was not aware that one could use env variables like so: <https://docs.docker.com/compose/environment-variables/>

I will definitely give it a look, and see if it is what I am looking for 👍🏻 

Closing this issue for now.

**Comment by carmatana** [comment]
Hello,

This is not working

declaring a variable in .env file is not safe, in this link is he explanantion

https://docs.docker.com/engine/swarm/secrets/

Use of secrets is the solution

https://docs.docker.com/compose/use-secrets/

Would be nice to have this added level of security

**Pull request closed without merging**
