### PR TITLE
Adding PersistentKeepalive

### LINKED ISSUE #44: KeepAlive
Could the PersistentKeepalive setting be implemented? Thanks!

### PR DESCRIPTION
**Pull request by Fastidious**
This PR closes #44.

### CODE REVIEW

**Comment by Fastidious** [comment]
I also added the ability to set the IP to which the web server will bind, to accommodate the use of a proxy when not using Docker.

**Comment by WeeJeWel** [comment]
I'd be happy to merge this if:

* You rename the env var to `WG_PERSISTENT_KEEPALIVE`
* The default is 0
* You remove the WEBHOST. I am not interested in customers using this without Docker.

**Comment by Fastidious** [comment]
Done. Baby steps. :-)

**Review by WeeJeWel — APPROVED** [review]

**Comment by WeeJeWel** [comment]
Please test your code next time: https://github.com/WeeJeWel/wg-easy/commit/d8eaafbcfb25d1c6d56cc10d4f895ed4d3fda5ff

**Comment by Fastidious** [comment]
> Please test your code next time: [d8eaafb](https://github.com/WeeJeWel/wg-easy/commit/d8eaafbcfb25d1c6d56cc10d4f895ed4d3fda5ff)

My apologies, and will be more careful. Thank you for merging!

**Pull request merged**
